language: cpp
sudo: required
dist: trusty
os: linux
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - libboost1.55-dev
      - libboost-test1.55-dev
      - g++-4.9
      - clang-5.0
script:
  - CC=gcc-5 CXX=g++-5 ./test.sh
  - CC=clang-5.0 CXX=clang++-5.0 ./test.sh
