language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost1.55-dev
      - libboost-test1.55-dev
script:
  - mkdir bin
  - cd bin
  - cmake .. -DCMAKE_CXX_FLAGS:STRING="-std=c++0x"
  - make
  - make test
  - cd ..
  - rm -rf bin
  - mkdir bin
  - cd bin
  - cmake ..
  - make
  - make test
